<template>
  <div class="loadingio-spinner-ellipsis-okucjf12p3"><div class="ldio-1qbopjuhv1h">
  <div></div><div></div><div></div><div></div><div></div>
  </div></div>
</template>

<script setup>
const props = defineProps({
    size:{
      type: String,
      default: "100px"
    }
})

</script>

<style lang="scss" scoped>
@keyframes ldio-1qbopjuhv1h {
   0% { transform: translate(12px,80px) scale(0); }
  25% { transform: translate(12px,80px) scale(0); }
  50% { transform: translate(12px,80px) scale(1); }
  75% { transform: translate(80px,80px) scale(1); }
 100% { transform: translate(148px,80px) scale(1); }
}
@keyframes ldio-1qbopjuhv1h-r {
   0% { transform: translate(148px,80px) scale(1); }
 100% { transform: translate(148px,80px) scale(0); }
}
@keyframes ldio-1qbopjuhv1h-c {
   0% { background: #e15b64 }
  25% { background: #abbd81 }
  50% { background: #f8b26a }
  75% { background: #f47e60 }
 100% { background: #e15b64 }
}
.ldio-1qbopjuhv1h div {
  position: absolute;
  width: 10px;
  height: 10px;
  border-radius: 50%;
  transform: translate(80px,80px) scale(1);
  background: #e15b64;
  animation: ldio-1qbopjuhv1h 1s infinite cubic-bezier(0,0.5,0.5,1);
}
.ldio-1qbopjuhv1h div:nth-child(1) {
  background: #f47e60;
  transform: translate(148px,80px) scale(1);
  animation: ldio-1qbopjuhv1h-r 0.25s infinite cubic-bezier(0,0.5,0.5,1), ldio-1qbopjuhv1h-c 1s infinite step-start;
}.ldio-1qbopjuhv1h div:nth-child(2) {
  animation-delay: -0.25s;
  background: #e15b64;
}.ldio-1qbopjuhv1h div:nth-child(3) {
  animation-delay: -0.2s;
  background: #f47e60;
}.ldio-1qbopjuhv1h div:nth-child(4) {
  animation-delay: -0.75s;
  background: #f8b26a;
}.ldio-1qbopjuhv1h div:nth-child(5) {
  animation-delay: -1s;
  background: #abbd81;
}
.loadingio-spinner-ellipsis-okucjf12p3 {
  width: 100px;
  height: 100px;
  display: inline-block;
  overflow: hidden;
  background: transparent;
}
.ldio-1qbopjuhv1h {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-1qbopjuhv1h div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>